# mkdir kafka2_data
# sudo chown -R 1001:1001 ./kafka2_data
# version: '3.8'

services:
    kafka-1:
        image: bitnami/kafka:latest
        container_name: kafka-1
        restart: unless-stopped
        ports:
            - '9092:9092'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CLUSTER_ID=haind_kk_cluster01
        volumes:
            - kafka1_data:/bitnami/kafka
        networks:
            - kafka-net
        # command: >
        #     bash -c "
        #       if [ ! -f /bitnami/kafka/data/meta.properties ]; then
        #         CLUSTER_ID=$$(kafka-storage.sh random-uuid) &&
        #         kafka-storage.sh format -t $$CLUSTER_ID -c /opt/bitnami/kafka/config/server.properties
        #       fi &&
        #       /opt/bitnami/scripts/kafka/run.sh
        #     "

    kafka-2:
        image: bitnami/kafka:latest
        container_name: kafka-2
        restart: unless-stopped
        ports:
            - '9094:9092'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_NODE_ID=2
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CLUSTER_ID=haind_kk_cluster01
        volumes:
            - kafka2_data:/bitnami/kafka
        networks:
            - kafka-net
        # command: >
        #     bash -c "
        #       if [ ! -f /bitnami/kafka/data/meta.properties ]; then
        #         CLUSTER_ID=$$(kafka-storage.sh random-uuid) &&
        #         kafka-storage.sh format -t $$CLUSTER_ID -c /opt/bitnami/kafka/config/server.properties
        #       fi &&
        #       /opt/bitnami/scripts/kafka/run.sh
        #     "

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        restart: unless-stopped
        ports:
            - '8080:8080'
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092
        depends_on:
            - kafka-1
            - kafka-2
        networks:
            - kafka-net

volumes:
    kafka1_data:
    kafka2_data:

networks:
    kafka-net:
        driver: bridge
