# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c70560f564f985189bac999e3ca9bc0"
name = "haind-app"
handle = "haind-app-1"
application_url = "https://minolta-brook-lasting-fake.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://minolta-brook-lasting-fake.trycloudflare.com/auth/callback",
  "https://minolta-brook-lasting-fake.trycloudflare.com/auth/shopify/callback",
  "https://minolta-brook-lasting-fake.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
