CREATE TABLE SAMPLE_TABLE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER
);

CREATE OR REPLACE PROCEDURE INSERT_SAMPLE_DATA AS
BEGIN
    FOR i IN 1..1000 LOOP
        INSERT INTO SAMPLE_TABLE (ID, NAME, AGE)
        VALUES (i, 'Name ' || i, MOD(i, 100) + 1);
    END LOOP;
    COMMIT;
END;


BEGIN
    INSERT_SAMPLE_DATA;
END;
